# Generated by Django 5.2.3 on 2025-06-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_battery_rating_review_camera_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='camera',
            field=models.CharField(default='Unknown Camera', max_length=200),
        ),
        migrations.AddField(
            model_name='specification',
            name='display_quality',
            field=models.CharField(default='Unknown Display', max_length=200),
        ),
        migrations.AddField(
            model_name='specification',
            name='processor',
            field=models.CharField(default='Unknown Processor', max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='ram',
            field=models.CharField(default='4 GB', max_length=50),
        ),
    ]
