# Generated by Django 5.2.3 on 2025-07-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_specification_camera_specification_display_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_video',
            field=models.FileField(blank=True, help_text='Upload a video review (only available for verified purchases)', null=True, upload_to='review_videos/%Y/%m/%d/'),
        ),
    ]
