# Generated by Django 5.2.3 on 2025-07-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='camera',
            new_name='rear_camera',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='display_quality',
        ),
        migrations.AddField(
            model_name='specification',
            name='audio_jack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='battery_capacity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='chipset',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='display_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='face_unlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='fingerprint_sensor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='front_camera',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='specification',
            name='gpu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='network_support',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='specification',
            name='nfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specification',
            name='resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specification',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specification',
            name='storage',
            field=models.CharField(default='128 GB', max_length=50),
        ),
        migrations.AddField(
            model_name='specification',
            name='video_recording',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='specification',
            name='weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='specification',
            name='wifi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
